# Generated by Django 4.0.3 on 2022-03-08 20:04

from django.db import migrations, models
import djongo.models.fields
import payAPI.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=50)),
                ('items', djongo.models.fields.ArrayField(model_container=payAPI.models.Product)),
                ('total_cents', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
