/*
 * External_interrupt.c
 *
 * Created: 2/14/2022 5:15:42 PM
 *  Author: Qaiaty
 */ 

#include "External_interrupt.h"

void Set_GlobalInterrupt(void)
{
	#if   GLOBAL_INTERRUPT_STATE == GLOBAL_INTERRUPT_ENABLE
	      SET_BIT(SREG,7);
	
	#elif GLOBAL_INTERRUPT_STATE == GLOBAL_INTERRUPT_DISABLE
	      CLR_BIT(SREG,7);
	#endif
}

void ExternalInterrupt0_INIT(void)
{
	Set_GlobalInterrupt();
	/*enable ext interrupt0 */
	SET_BIT(GICR,6);
	
	#if    EXTERNAL_INTERRUPT0_TRIGGER == INT_TRIGGER_LOW_LEVEL
	       CLR_BIT(MCUCR,0);
		   CLR_BIT(MCUCR,1);
	#elif  EXTERNAL_INTERRUPT0_TRIGGER == INT_TRIGGER_RISING_EDGE
	       SET_BIT(MCUCR,0);
		   SET_BIT(MCUCR,1);
	#elif  EXTERNAL_INTERRUPT0_TRIGGER == INT_TRIGGER_FALLING_EDGE
		   CLR_BIT(MCUCR,0);
		   SET_BIT(MCUCR,1);
	#elif  EXTERNAL_INTERRUPT0_TRIGGER == INT_TRIGGER_ANY_LOGICAL_CHANGE
	       SET_BIT(MCUCR,0);
		   CLR_BIT(MCUCR,1);
	#endif
	
}

void ExternalInterrupt1_INIT(void)
{
	Set_GlobalInterrupt();
	/*enable ext interrupt0 */
	SET_BIT(GICR,7);
	#if    EXTERNAL_INTERRUPT1_TRIGGER == INT_TRIGGER_LOW_LEVEL
	CLR_BIT(MCUCR,2);
	CLR_BIT(MCUCR,3);
	#elif  EXTERNAL_INTERRUPT1_TRIGGER == INT_TRIGGER_RISING_EDGE
	SET_BIT(MCUCR,2);
	SET_BIT(MCUCR,3);
	#elif  EXTERNAL_INTERRUPT1_TRIGGER == INT_TRIGGER_FALLING_EDGE
	CLR_BIT(MCUCR,2);
	SET_BIT(MCUCR,3);
	#elif  EXTERNAL_INTERRUPT1_TRIGGER == INT_TRIGGER_ANY_LOGICAL_CHANGE
	SET_BIT(MCUCR,2);
	CLR_BIT(MCUCR,3);
	#endif
	
}

void ExternalInterrupt2_INIT(void)
{
	Set_GlobalInterrupt();
	/*enable ext interrupt0 */
	SET_BIT(GICR,5);
	
	#if  EXTERNAL_INTERRUPT2_TRIGGER == INT_TRIGGER_RISING_EDGE
	SET_BIT(MCUCSR,6);
	#elif  EXTERNAL_INTERRUPT2_TRIGGER == INT_TRIGGER_FALLING_EDGE
	CLR_BIT(MCUCSR,6);
	#endif
	
}